name: CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Frontend Dependencies
      run: npm install
      
    # Команда npm test запустится, если в проекте есть тесты. 
    # В Create React App она есть по умолчанию.
    - name: Run Tests
      run: npm test -- --passWithNoTests